### ISSUE TITLE
emupdk v.s ucsim

### ISSUE THREAD

**Issue by spth** [free-pdk/fppa-pdk-tools#3]
For pdk14, there also is another emulator:
ucsim has support for pdk14 (emulates the PMCS132B, though so far just the core, no peripherals yet).

Since the SDCC regression tests and ucsim interact well (ucsim is also used for regression testing of some other SDCC backends), that one is used in the automated regression testing of pdk14.

ucsim does not yet support the pdk13 or pdk15 (see https://sourceforge.net/p/sdcc/feature-requests/619/).

I wonder if it makes sense to keep developing two different simulators.

Philipp

**Comment by freepdk** [comment]
Right now there is only the 14 bit simulator (also without peripherals) implemented.
I quickly wrote it to understand some of the magic (calibration) code inserted from IDE.

Do you have any pointer for how to use ucsim easily? The learning curve seems a bit steep if you have no experience with it.

**Comment by spth** [comment]
Invoke like

~~~~
spdk test.ihx
~~~~

Simulate until next breakpoint or end via

~~~~
run
~~~~

Add breakpoint via

~~~~
break <address>
~~~~

Which works for at least decimal and hexadecimal (with 0x prefix) addresses.
Simulate for a specific number of cycles via

~~~~
step <n>
~~~~

Show memory contents via

~~~~
dump rom <address>
dump ram <address>
~~~~

There is a lot more, which can be discovered via

~~~~
help
~~~~
