### ISSUE TITLE
fixupHighCode in init function prevent emulator to work

### ISSUE THREAD

**Issue by Bibi2424** [free-pdk/fppa-pdk-tools#4]
I tracked down that you move the fixupHighCode logic from emupdk.c to each specific cpu init function but the problem is that you "fix" the code before loading the pdk file.
In ```emuCPUloadPDK(...)``` (_emucpu.c_), you first init the cpu (which patch the HighCode) but after you load the code from the PDK file which revert the modification and prevents the emulator to work.

**Comment by freepdk** [comment]
Fixed with commit 2b263cbdcd6e5f6d68527d3a824eb001c1a53dfe.

However ucsim in SDCC seems to be a better choice for future development of a PC based simulator.
See issue #3.
